from PyQt6 import QtCore, QtGui, QtWidgets


class Signup(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 692)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    border-image: url(:/arkaplan/1.1.1.jpg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.topMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.topMenu.setGeometry(QtCore.QRect(0, 0, 959, 151))
        self.topMenu.setObjectName("topMenu")
        self.label = QtWidgets.QLabel(parent=self.topMenu)
        self.label.setGeometry(QtCore.QRect(440, 90, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color : white;")
        self.label.setObjectName("label")
        self.midMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.midMenu.setGeometry(QtCore.QRect(0, 157, 959, 251))
        self.midMenu.setStyleSheet("background: transparent;")
        self.midMenu.setObjectName("midMenu")
        self.label_2 = QtWidgets.QLabel(parent=self.midMenu)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.midMenu)
        self.label_3.setGeometry(QtCore.QRect(330, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : white;")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.midMenu)
        self.lineEdit.setGeometry(QtCore.QRect(330, 50, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 10);\n"
"border: none;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.midMenu)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 160, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 10);\n"
"border: none;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.bottomMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.bottomMenu.setGeometry(QtCore.QRect(0, 414, 959, 261))
        self.bottomMenu.setObjectName("bottomMenu")
        self.signupBtn = QtWidgets.QPushButton(parent=self.bottomMenu)
        self.signupBtn.setGeometry(QtCore.QRect(410, 0, 140, 35))
        self.signupBtn.setStyleSheet("    border-radius: 10px;\n"
"    background-color: rgb(255, 0, 0);")
        self.signupBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/yeniÖnek/icons/icons8-dumbbell-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.signupBtn.setIcon(icon)
        self.signupBtn.setIconSize(QtCore.QSize(40, 40))
        self.signupBtn.setObjectName("signupBtn")
        self.loginBtn = QtWidgets.QPushButton(parent=self.bottomMenu)
        self.loginBtn.setGeometry(QtCore.QRect(440, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("color : red;\n"
"background : transparent;")
        self.loginBtn.setObjectName("loginBtn")
        self.label_4 = QtWidgets.QLabel(parent=self.bottomMenu)
        self.label_4.setGeometry(QtCore.QRect(410, 90, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color : white;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SIGNUP"))
        self.label_2.setText(_translate("MainWindow", "e-mail adress"))
        self.label_3.setText(_translate("MainWindow", "password"))
        self.loginBtn.setText(_translate("MainWindow", "Log in"))
        self.label_4.setText(_translate("MainWindow", "Already have an account?"))
